# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  # vmImage: ubuntu-latest
  name: "my Mac"

steps:

# (Optional) Confirm JAVA_HOME is set correctly
- script: |
    echo "JAVA_HOME = $JAVA_HOME"
    java -version
  displayName: 'Verify Java installation'

# Step 1: Build with Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkDirectory: '/Library/Java/JavaVirtualMachines/jdk-22.jdk/Contents/Home' # Your JDK 22 path
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package -DskipTests=true'

# Step 2: Publish build artifact
- task: CopyFiles@2
  inputs:
    contents: 'target/*.jar'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'springboot-jar'
    publishLocation: 'Container'

# Step 3: Deploy to Azure App Service
# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: 'azure-service-employee-api'  # Your service connection name
#     appType: 'webAppLinux'
#     appName: 'employee-apis'  # Your App Service name
#     package: '$(Build.ArtifactStagingDirectory)/*.jar'
#     runtimeStack: 'JAVA|21-java21'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-service-employee-api'
    appType: 'webAppLinux'
    appName: 'employee-apis'
    package: '$(System.DefaultWorkingDirectory)/target/*.jar'
    runtimeStack: 'JAVA|21-java21'